#ifndef MSP_H
#define MSP_H

#define MSP_URL_DEFAULT		"https://www.ageofelements.org/sounds/"

#define MSP_SOUND_APPEAR	"appear*"
#define MSP_SOUND_ARROW		"arrow*"
#define MSP_SOUND_BASHED	"bashed*"
#define MSP_SOUND_BIGBY		"bigby*"
#define MSP_SOUND_BLESS		"bless*"
#define MSP_SOUND_BLOCKED	"blocked*"
#define MSP_SOUND_CHIMES	"chimes*"
#define MSP_SOUND_CHOKE		"choke*"
#define MSP_SOUND_CLAPPING	"clapping*"
#define MSP_SOUND_COW		"cow*"
#define MSP_SOUND_DEATH		"death*"
#define MSP_SOUND_DECAP		"decap*"
#define MSP_SOUND_DEFAULT	"default*"
#define MSP_SOUND_DOH		"doh*"
#define MSP_SOUND_DOOROPEN	"dooropen*"
#define MSP_SOUND_DOORUNLOCK	"doorunlock*"
#define MSP_SOUND_DRINK		"drink*"
#define MSP_SOUND_EXPLODE	"explode*"
#define MSP_SOUND_FALLSCREAM	"fallscream*"
#define MSP_SOUND_FART		"fart*"
#define MSP_SOUND_FIREBALL	"fireball*"
#define MSP_SOUND_GULP		"gulp*"
#define MSP_SOUND_HAHA		"haha*"
#define MSP_SOUND_HOWL		"howl*"
#define MSP_SOUND_KNOCK		"knock*"
#define MSP_SOUND_LEVEL_GAIN	"level_gain*"
#define MSP_SOUND_LEVER		"lever*"
#define MSP_SOUND_LIGHTNING	"lightning*"
#define MSP_SOUND_MAGICSHIELD	"magicshield*"
#define MSP_SOUND_MISSED	"missed*"
#define MSP_SOUND_OUCH		"ouch*"
#define MSP_SOUND_PLOP		"plop*"
#define MSP_SOUND_POISONED	"poisoned*"
#define MSP_SOUND_PUNCH		"punch*"
#define MSP_SOUND_RECONNECT	"reconnect*"
#define MSP_SOUND_RESET		"reset*"
#define MSP_SOUND_SHOCK		"shock*"
#define MSP_SOUND_WIND		"wind*"
#define MSP_SOUND_SPELLDAM	"spelldam*"
#define MSP_SOUND_SPLAT		"splat*"
#define MSP_SOUND_TORNADO	"tornado*"
#define MSP_SOUND_TRAP		"trap*"
#define MSP_SOUND_TRUMPETS	"trumpets*"
#define MSP_SOUND_WATER		"water*"
#define MSP_SOUND_WEB		"web*"
#define MSP_SOUND_WOOHOO	"woohoo*"

// Recommend to not change anything below this line.

#define MSP_SOUND		"SOUND"
#define MSP_MUSIC		"MUSIC"

#define MSP_FILENAME		"fName"
#define MSP_FILENAME_OFF	"Off"

#define MSP_VOLUME 		"V"
#define MSP_VOLUME_LOUD		"100"
#define MSP_VOLUME_HIGH		"75"
#define MSP_VOLUME_DEFAULT	"50"
#define MSP_VOLUME_LOW		"25"

#define MSP_LENGTH 		"L"
#define MSP_LENGTH_DEFAULT	"1"
#define MSP_LENGTH_REPEAT	"-1"

#define MSP_PRIORITY 		"P"
#define MSP_PRIORITY_MAX	"100"
#define MSP_PRIORITY_HIGH	"75"
#define MSP_PRIORITY_DEFAULT	"50"
#define MSP_PRIORITY_LOW	"25"

#define MSP_CONTINUE		"C"
#define MSP_CONTINUE_DEFAULT	"1"
#define MSP_CONTINUE_RESTART	"0"

#define MSP_TYPE		"T"
#define MSP_URL			"U"

#endif // MSP_H
